version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.5.73.84
      KAFKA_CREATE_TOPICS: "front:1:1,rear:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  trifecta:
    image: janschultecom/docker-trifecta
    ports:
      - "9000:9000"
    environment:
      ZK_HOST: 10.5.73.84:2181
  blackhole:
    image: tecnativa/smtp-sink:latest
    ports:
      - "30025:25"